development:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USERNAME} password=${DB_PASSWORD} sslmode=disable
  dir: scripts/migrations/postgres
  table: gorp_migrations
