version: "3.1"

services:
    go-clean-arch-be:
        image: docker.pkg.github.com/capioteknologi/go-clean-arch-be/go-clean-arch-be:latest
        container_name: go-clean-arch-be
        env_file:
            - .env
        ports:
        - 3000:3000
        restart: always
        command: ["rest"]

    go-clean-arch-be-cron:
        image: docker.pkg.github.com/capioteknologi/go-clean-arch-be/go-clean-arch-be:latest
        container_name: go-clean-arch-be-cron
        env_file:
            - .env
        restart: always
        depends_on: 
            - go-clean-arch-be
        command: ["cron"]