name: Development CI

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: capioteknologi/go-clean-arch-be/go-clean-arch-be
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest"
          dockerfile: build/Dockerfile

