name: Production CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Production Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: capioteknologi/alhikmah-be/alhikmah-be
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          tags: "release-${{github.ref_name}}"
          dockerfile: build/Dockerfile
